DROP TABLE IF EXISTS listings_i18n;
DROP TABLE IF EXISTS listings;
DROP TABLE IF EXISTS accounts_roles;
DROP TABLE IF EXISTS languages;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS accounts;

DROP TYPE IF EXISTS gender CASCADE

DROP EXTENSION IF EXISTS postgis cascade;
